#![cfg(feature = "test-internals")]
#![allow(missing_docs)]

//! A7 QUIC application-data loopback proof over real loopback UDP.
//!
//! This verifies the current native QUIC data-plane boundary after A1-A6:
//! application STREAM and DATAGRAM frames are generated by `NativeQuicConnection`,
//! protected as 1-RTT short-header packets by `ConnectionRouter`, carried through
//! real `QuicUdpEndpoint` sockets on 127.0.0.1, unprotected by the peer router,
//! and surfaced as byte-identical application payloads. It also pins the G4
//! security-review boundaries for replay rejection and pre-validation
//! anti-amplification over the same real UDP endpoint path.

use asupersync::bytes::{Bytes, BytesMut};
use asupersync::cx::Cx;
use asupersync::net::atp::protocol::quic_frames::QuicFrame;
use asupersync::net::atp::quic::AtpPacketProtection;
use asupersync::net::quic_core::{ConnectionId, LongHeader, LongPacketType, PacketHeader};
use asupersync::net::quic_native::{
    ConnectionRouter, ConnectionRouterError, NativeQuicConnection, NativeQuicConnectionConfig,
    NativeQuicConnectionError, OutgoingPacket, PacketProtectionSpace, QuicHandshakeTranscript,
    QuicUdpEndpoint, QuicUdpEndpointConfig, RoutingResult, StreamId,
};
use asupersync::time::{timeout, wall_now};
use futures_lite::future::block_on;
use std::net::SocketAddr;
use std::time::{Duration, Instant};

const CONNECTION_ID_BYTES: &[u8] = b"a7udp001";
const UDP_RECEIVE_TIMEOUT: Duration = Duration::from_secs(2);

fn test_cx() -> Cx {
    Cx::for_testing()
}

fn padded_initial_packet(
    dst_cid: ConnectionId,
    src_cid: ConnectionId,
    packet_number: u64,
) -> Vec<u8> {
    let mut payload = BytesMut::new();
    QuicFrame::Ping
        .encode(&mut payload)
        .expect("PING frame encodes");
    QuicFrame::Padding { length: 1_200 }
        .encode(&mut payload)
        .expect("Initial padding encodes");

    let header = PacketHeader::Long(LongHeader {
        packet_type: LongPacketType::Initial,
        version: 1,
        dst_cid,
        src_cid,
        token: Vec::new(),
        payload_length: (1 + payload.len()) as u64,
        packet_number,
        packet_number_len: 1,
    });
    let mut packet = Vec::new();
    header.encode(&mut packet).expect("Initial header encodes");
    packet.extend_from_slice(&payload);
    packet
}

async fn one_rtt_protection(cx: &Cx, server_side: bool) -> AtpPacketProtection {
    let mut transcript = QuicHandshakeTranscript::new();
    transcript.record("client_initial", b"a7 client hello");
    transcript.record("server_handshake", b"a7 server hello");
    let mut protection = if server_side {
        AtpPacketProtection::new_server(true).expect("server ATP packet protection")
    } else {
        AtpPacketProtection::new_client(true).expect("client ATP packet protection")
    };
    protection
        .derive_keys(
            cx,
            PacketProtectionSpace::OneRtt,
            &transcript,
            b"asupersync a7 real udp protected app data",
        )
        .await
        .expect("derive 1-RTT keys");
    protection
}

fn establish_for_application_data(
    cx: &Cx,
    connection: &mut NativeQuicConnection,
) -> Result<(), NativeQuicConnectionError> {
    connection.begin_handshake(cx)?;
    connection.on_handshake_keys_available(cx)?;
    connection.on_1rtt_keys_available(cx)?;
    connection.record_verified_server_identity();
    connection.on_handshake_confirmed(cx)
}

async fn build_router_pair(
    cx: &Cx,
    connection_id: ConnectionId,
    client_addr: SocketAddr,
    server_addr: SocketAddr,
) -> (ConnectionRouter, ConnectionRouter) {
    let config = NativeQuicConnectionConfig::default();
    let mut client = ConnectionRouter::new(config);
    let mut server = ConnectionRouter::new(config);

    client
        .create_connection(cx, connection_id, server_addr, false)
        .await
        .expect("create client connection");
    server
        .create_connection(cx, connection_id, client_addr, true)
        .await
        .expect("create server connection");

    client
        .install_packet_protection(cx, connection_id, one_rtt_protection(cx, false).await)
        .expect("install client packet protection");
    server
        .install_packet_protection(cx, connection_id, one_rtt_protection(cx, true).await)
        .expect("install server packet protection");

    establish_for_application_data(
        cx,
        client
            .connection_mut_for_testing(cx, connection_id)
            .expect("client connection"),
    )
    .expect("client reaches app data");
    establish_for_application_data(
        cx,
        server
            .connection_mut_for_testing(cx, connection_id)
            .expect("server connection"),
    )
    .expect("server reaches app data");

    (client, server)
}

async fn send_router_packets_over_udp(
    cx: &Cx,
    router: &mut ConnectionRouter,
    endpoint: &mut QuicUdpEndpoint,
    connection_id: ConnectionId,
    dst_addr: SocketAddr,
) -> Vec<Vec<u8>> {
    let packets = router
        .drain_application_data_for_testing(cx, connection_id, dst_addr, Instant::now())
        .await
        .expect("drain protected app-data packets");
    assert!(
        !packets.is_empty(),
        "expected at least one protected packet"
    );
    let captured = packets
        .iter()
        .map(|packet| packet.data.clone())
        .collect::<Vec<_>>();
    let report = endpoint
        .send_batch(cx, &packets)
        .await
        .expect("send protected packet over real UDP");
    assert_eq!(report.packets_processed, packets.len());
    assert!(report.error.is_none());
    captured
}

async fn receive_and_route_udp_batch(
    cx: &Cx,
    endpoint: &mut QuicUdpEndpoint,
    router: &mut ConnectionRouter,
) -> Result<usize, ConnectionRouterError> {
    let packets = timeout(
        wall_now(),
        UDP_RECEIVE_TIMEOUT,
        endpoint.receive_batch(cx, 16),
    )
    .await
    .expect("timed out waiting for protected UDP packet")
    .expect("receive protected packet over real UDP");
    assert!(!packets.is_empty(), "expected UDP packet batch");

    let mut routed = 0;
    for packet in packets {
        match router.route_packet(cx, packet).await? {
            RoutingResult::Routed { .. } => routed += 1,
            other => panic!("expected routed app-data packet, got {other:?}"),
        }
    }
    Ok(routed)
}

#[test]
fn protected_stream_and_datagrams_cross_real_loopback_udp() {
    block_on(async {
        let cx = test_cx();
        let connection_id = ConnectionId::new(CONNECTION_ID_BYTES).expect("connection id");
        let udp_config = QuicUdpEndpointConfig::default();
        let mut client_udp =
            QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config.clone())
                .await
                .expect("bind client UDP");
        let mut server_udp = QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config)
            .await
            .expect("bind server UDP");
        let client_addr = client_udp.local_addr();
        let server_addr = server_udp.local_addr();
        let (mut client, mut server) =
            build_router_pair(&cx, connection_id, client_addr, server_addr).await;

        let stream: StreamId;
        {
            let conn = client
                .connection_mut_for_testing(&cx, connection_id)
                .expect("client connection");
            stream = conn.open_local_bidi(&cx).expect("open control stream");
            conn.write_stream_bytes(
                &cx,
                stream,
                Bytes::from_static(b"MANIFEST control bytes over UDP"),
                true,
            )
            .expect("queue control bytes");
            conn.send_datagram(&cx, Bytes::from_static(b"symbol-0"))
                .expect("queue datagram 0");
            conn.send_datagram(&cx, Bytes::from_static(b"symbol-1"))
                .expect("queue datagram 1");
        }

        let wire_packets = send_router_packets_over_udp(
            &cx,
            &mut client,
            &mut client_udp,
            connection_id,
            server_addr,
        )
        .await;
        assert!(
            wire_packets
                .iter()
                .all(|packet| !packet.windows(b"MANIFEST".len()).any(|w| w == b"MANIFEST")),
            "protected UDP packets must not expose plaintext control bytes"
        );

        let routed = receive_and_route_udp_batch(&cx, &mut server_udp, &mut server)
            .await
            .expect("route");
        assert!(routed >= 1);

        let conn = server
            .connection_mut_for_testing(&cx, connection_id)
            .expect("server connection");
        let control = conn
            .read_stream_bytes(&cx, stream, 1024)
            .expect("read control bytes");
        assert_eq!(control.as_ref(), b"MANIFEST control bytes over UDP");
        assert!(conn.is_stream_read_eof(stream).expect("control eof"));
        assert_eq!(conn.recv_datagram().as_deref(), Some(&b"symbol-0"[..]));
        assert_eq!(conn.recv_datagram().as_deref(), Some(&b"symbol-1"[..]));
        assert!(conn.recv_datagram().is_none());
    });
}

#[test]
fn datagram_loss_is_tolerated_and_later_symbols_still_arrive() {
    block_on(async {
        let cx = test_cx();
        let connection_id = ConnectionId::new(b"a7loss01").expect("connection id");
        let udp_config = QuicUdpEndpointConfig::default();
        let mut client_udp =
            QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config.clone())
                .await
                .expect("bind client UDP");
        let mut server_udp = QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config)
            .await
            .expect("bind server UDP");
        let (mut client, mut server) = build_router_pair(
            &cx,
            connection_id,
            client_udp.local_addr(),
            server_udp.local_addr(),
        )
        .await;

        {
            let conn = client
                .connection_mut_for_testing(&cx, connection_id)
                .expect("client connection");
            conn.send_datagram(&cx, Bytes::from_static(b"lost-symbol"))
                .expect("queue lost datagram");
        }
        let dropped = client
            .drain_application_data_for_testing(
                &cx,
                connection_id,
                server_udp.local_addr(),
                Instant::now(),
            )
            .await
            .expect("drain packet to drop");
        assert_eq!(dropped.len(), 1);

        {
            let conn = client
                .connection_mut_for_testing(&cx, connection_id)
                .expect("client connection");
            conn.send_datagram(&cx, Bytes::from_static(b"delivered-symbol"))
                .expect("queue delivered datagram");
        }
        send_router_packets_over_udp(
            &cx,
            &mut client,
            &mut client_udp,
            connection_id,
            server_udp.local_addr(),
        )
        .await;
        receive_and_route_udp_batch(&cx, &mut server_udp, &mut server)
            .await
            .expect("route delivered packet");

        let conn = server
            .connection_mut_for_testing(&cx, connection_id)
            .expect("server connection");
        assert_eq!(
            conn.recv_datagram().as_deref(),
            Some(&b"delivered-symbol"[..])
        );
        assert!(
            conn.recv_datagram().is_none(),
            "dropped datagram must not surface later"
        );
    });
}

#[test]
fn tampered_protected_udp_packet_fails_closed() {
    block_on(async {
        let cx = test_cx();
        let connection_id = ConnectionId::new(b"a7tamper").expect("connection id");
        let udp_config = QuicUdpEndpointConfig::default();
        let mut client_udp =
            QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config.clone())
                .await
                .expect("bind client UDP");
        let mut server_udp = QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config)
            .await
            .expect("bind server UDP");
        let (mut client, mut server) = build_router_pair(
            &cx,
            connection_id,
            client_udp.local_addr(),
            server_udp.local_addr(),
        )
        .await;

        {
            let conn = client
                .connection_mut_for_testing(&cx, connection_id)
                .expect("client connection");
            conn.send_datagram(&cx, Bytes::from_static(b"tamper-target"))
                .expect("queue tamper target");
        }
        let mut packets = client
            .drain_application_data_for_testing(
                &cx,
                connection_id,
                server_udp.local_addr(),
                Instant::now(),
            )
            .await
            .expect("drain protected packet");
        assert_eq!(packets.len(), 1);
        let packet = &mut packets[0].data;
        let last = packet
            .last_mut()
            .expect("protected packet includes authentication tag");
        *last ^= 0x80;
        client_udp
            .send_batch(&cx, &packets)
            .await
            .expect("send tampered packet");

        let err = receive_and_route_udp_batch(&cx, &mut server_udp, &mut server)
            .await
            .expect_err("tampered AEAD packet must fail closed");
        assert!(
            matches!(err, ConnectionRouterError::PacketProcessingFailed { .. }),
            "expected packet-processing failure, got {err:?}"
        );
        let conn = server
            .connection_mut_for_testing(&cx, connection_id)
            .expect("server connection");
        assert!(conn.recv_datagram().is_none());
    });
}

#[test]
fn replayed_protected_udp_packet_fails_closed_without_duplicate_delivery() {
    block_on(async {
        let cx = test_cx();
        let connection_id = ConnectionId::new(b"a7replay").expect("connection id");
        let udp_config = QuicUdpEndpointConfig::default();
        let mut client_udp =
            QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config.clone())
                .await
                .expect("bind client UDP");
        let mut server_udp = QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config)
            .await
            .expect("bind server UDP");
        let (mut client, mut server) = build_router_pair(
            &cx,
            connection_id,
            client_udp.local_addr(),
            server_udp.local_addr(),
        )
        .await;

        {
            let conn = client
                .connection_mut_for_testing(&cx, connection_id)
                .expect("client connection");
            conn.send_datagram(&cx, Bytes::from_static(b"replay-target"))
                .expect("queue replay target");
        }
        let packets = client
            .drain_application_data_for_testing(
                &cx,
                connection_id,
                server_udp.local_addr(),
                Instant::now(),
            )
            .await
            .expect("drain protected packet");
        assert_eq!(packets.len(), 1);
        client_udp
            .send_batch(&cx, &packets)
            .await
            .expect("send original packet");

        let routed = receive_and_route_udp_batch(&cx, &mut server_udp, &mut server)
            .await
            .expect("route original packet");
        assert_eq!(routed, 1);
        let conn = server
            .connection_mut_for_testing(&cx, connection_id)
            .expect("server connection");
        assert_eq!(conn.recv_datagram().as_deref(), Some(&b"replay-target"[..]));
        assert!(conn.recv_datagram().is_none());

        client_udp
            .send_batch(&cx, &packets)
            .await
            .expect("re-send captured packet");
        let err = receive_and_route_udp_batch(&cx, &mut server_udp, &mut server)
            .await
            .expect_err("replayed protected packet must fail closed");
        match err {
            ConnectionRouterError::PacketProcessingFailed { reason, .. } => {
                assert!(
                    reason.contains("ReplayedNonce"),
                    "expected replay rejection, got {reason}"
                );
            }
            other => panic!("expected packet-processing failure, got {other:?}"),
        }
        let conn = server
            .connection_mut_for_testing(&cx, connection_id)
            .expect("server connection");
        assert!(
            conn.recv_datagram().is_none(),
            "replayed datagram must not be delivered twice"
        );
    });
}

#[test]
fn pre_validation_initial_responses_stay_within_real_udp_amplification_budget() {
    block_on(async {
        let cx = test_cx();
        let connection_id = ConnectionId::new(b"a7amplim").expect("connection id");
        let client_cid = ConnectionId::new(b"a7ampcli").expect("client connection id");
        let udp_config = QuicUdpEndpointConfig::default();
        let mut client_udp =
            QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config.clone())
                .await
                .expect("bind client UDP");
        let mut server_udp = QuicUdpEndpoint::bind(&cx, "127.0.0.1:0".parse().unwrap(), udp_config)
            .await
            .expect("bind server UDP");
        let client_addr = client_udp.local_addr();
        let server_addr = server_udp.local_addr();
        let mut server = ConnectionRouter::new(NativeQuicConnectionConfig::default());
        server
            .create_connection(&cx, connection_id, client_addr, true)
            .await
            .expect("create pre-validation server connection");

        let mut inbound_total = 0usize;
        let mut outbound_total = 0usize;

        for packet_number in 0..3 {
            let initial = padded_initial_packet(connection_id, client_cid, packet_number);
            let initial_len = initial.len();
            let sent = client_udp
                .send_batch(
                    &cx,
                    &[OutgoingPacket {
                        dst_addr: server_addr,
                        data: initial,
                        send_time: None,
                    }],
                )
                .await
                .expect("send padded Initial over real UDP");
            assert_eq!(sent.bytes_processed, initial_len);

            let received = timeout(
                wall_now(),
                UDP_RECEIVE_TIMEOUT,
                server_udp.receive_batch(&cx, 1),
            )
            .await
            .expect("timed out waiting for Initial")
            .expect("receive padded Initial over real UDP");
            assert_eq!(received.len(), 1);
            let inbound_bytes = received
                .iter()
                .map(|packet| packet.data.len())
                .sum::<usize>();
            assert_eq!(inbound_bytes, initial_len);
            inbound_total = inbound_total.saturating_add(inbound_bytes);

            let mut responses = Vec::new();
            for packet in received {
                let routed = server
                    .route_packet(&cx, packet)
                    .await
                    .expect("route Initial");
                assert!(
                    matches!(routed, RoutingResult::Routed { .. }),
                    "expected routed Initial response, got {routed:?}"
                );
                if let RoutingResult::Routed {
                    outgoing_packets, ..
                } = routed
                {
                    responses.extend(outgoing_packets);
                }
            }
            assert!(
                !responses.is_empty(),
                "pre-validation Initial should elicit an ACK response"
            );

            let response_bytes = responses
                .iter()
                .map(|packet| packet.data.len())
                .sum::<usize>();
            assert!(
                response_bytes <= inbound_bytes.saturating_mul(3),
                "pre-validation response exceeded 3x budget: inbound={inbound_bytes}, outbound={response_bytes}"
            );

            let delivered = server_udp
                .send_batch(&cx, &responses)
                .await
                .expect("send pre-validation response over real UDP");
            assert_eq!(delivered.bytes_processed, response_bytes);
            assert!(
                delivered.bytes_processed <= inbound_bytes.saturating_mul(3),
                "real UDP send exceeded 3x budget: inbound={inbound_bytes}, outbound={}",
                delivered.bytes_processed
            );

            let client_received = timeout(
                wall_now(),
                UDP_RECEIVE_TIMEOUT,
                client_udp.receive_batch(&cx, 16),
            )
            .await
            .expect("timed out waiting for response")
            .expect("receive pre-validation response over real UDP");
            let client_response_bytes = client_received
                .iter()
                .map(|packet| packet.data.len())
                .sum::<usize>();
            assert_eq!(client_response_bytes, response_bytes);

            outbound_total = outbound_total.saturating_add(delivered.bytes_processed);
            let stats = server.connection_stats();
            assert_eq!(stats.active_connections, 1);
            assert_eq!(stats.established_connections, 0);
            assert_eq!(stats.pending_connections, 1);
        }

        assert!(
            outbound_total <= inbound_total.saturating_mul(3),
            "cumulative pre-validation UDP responses exceeded 3x budget: inbound={inbound_total}, outbound={outbound_total}"
        );
    });
}

#[cfg(feature = "tls")]
mod tls_identity {
    use super::*;
    use asupersync::net::quic_native::tls::QuicServerIdentityVerifier;
    use asupersync::net::quic_native::{QuicConnectionState, QuicTlsError};
    use asupersync::tls::{Certificate, CertificateChain, RootCertStore};
    use std::time::Duration;

    const TEST_CERT_PEM: &[u8] = include_bytes!("fixtures/tls/server.crt");

    fn valid_fixture_time() -> rustls_pki_types::UnixTime {
        rustls_pki_types::UnixTime::since_unix_epoch(Duration::from_secs(1_780_000_000))
    }

    fn trusted_fixture_material() -> (QuicServerIdentityVerifier, CertificateChain) {
        let certs = Certificate::from_pem(TEST_CERT_PEM).expect("fixture cert parses");
        let mut roots = RootCertStore::empty();
        roots
            .add(&certs[0])
            .expect("self-signed fixture can be a test trust anchor");
        let verifier = QuicServerIdentityVerifier::from_root_store(roots).expect("verifier builds");
        (verifier, CertificateChain::from(certs))
    }

    #[test]
    fn test_ca_accepts_localhost_and_bad_hostname_fails_closed() {
        let cx = test_cx();
        let (verifier, chain) = trusted_fixture_material();
        let mut client = NativeQuicConnection::new(NativeQuicConnectionConfig::default());
        client.begin_handshake(&cx).expect("begin handshake");
        client
            .on_handshake_keys_available(&cx)
            .expect("handshake keys");
        client.on_1rtt_keys_available(&cx).expect("1-RTT keys");
        client
            .verify_server_identity_and_confirm_handshake(
                &cx,
                &verifier,
                "localhost",
                chain,
                valid_fixture_time(),
            )
            .expect("valid localhost test certificate confirms handshake");
        assert_eq!(client.state(), QuicConnectionState::Established);
        assert!(client.can_send_1rtt());

        let (verifier, chain) = trusted_fixture_material();
        let mut bad_client = NativeQuicConnection::new(NativeQuicConnectionConfig::default());
        bad_client.begin_handshake(&cx).expect("begin handshake");
        bad_client
            .on_handshake_keys_available(&cx)
            .expect("handshake keys");
        bad_client.on_1rtt_keys_available(&cx).expect("1-RTT keys");
        let err = bad_client
            .verify_server_identity_and_confirm_handshake(
                &cx,
                &verifier,
                "wrong-host.example",
                chain,
                valid_fixture_time(),
            )
            .expect_err("wrong hostname must fail closed");
        assert!(matches!(
            err,
            NativeQuicConnectionError::Tls(QuicTlsError::ServerCertificateRejected { .. })
        ));
        assert_eq!(bad_client.state(), QuicConnectionState::Handshaking);
        assert!(!bad_client.can_send_1rtt());
    }
}
