//! RFC 6330 decode-correctness matrix (bead bd-3uox5).
//!
//! The existing `tests/raptorq_proof_partial_loss_e2e.rs` proves the
//! `InactivationDecoder::decode_with_proof` happy path for a single
//! configuration (k=12, four scattered source drops). This harness widens
//! decode-correctness coverage across a deterministic matrix of source-block
//! sizes and loss *shapes* — scattered, burst, endpoint, full-source-erasure,
//! and no-loss — each asserting byte-identical recovery and proof replay.
//!
//! Every scenario is verifiable by construction (recovered source must equal
//! the original bytes), so no external golden vector is needed. Inputs are
//! fixed `DetRng` seeds for reproducibility, and each scenario emits a
//! structured JSON line capturing seed / config / loss pattern / outcome.
//!
//! # Repro
//!
//! ```text
//! rch exec -- env CARGO_TARGET_DIR=/data/tmp/rch_target_asupersync_test \
//!   cargo test --test raptorq_decode_correctness_matrix -- --nocapture
//! ```

#![allow(missing_docs)]

use asupersync::raptorq::decoder::{InactivationDecoder, ReceivedSymbol};
use asupersync::raptorq::systematic::SystematicEncoder;
use asupersync::types::ObjectId;
use asupersync::util::DetRng;

const OBJECT_ID_HIGH: u64 = 0x0BAD_C0DE_1234_5678;
const OBJECT_ID_LOW: u64 = 0x8765_4321_FEED_FACE;

/// Loss shape applied to the source-symbol ESIs of a block.
#[derive(Debug, Clone, Copy)]
enum LossShape {
    /// No source symbols dropped (baseline systematic pass-through).
    None,
    /// Individually listed source ESIs dropped.
    Scattered(&'static [usize]),
    /// A contiguous run `[start, start + len)` dropped.
    Burst { start: usize, len: usize },
    /// The first and last source ESIs dropped.
    Endpoints,
    /// Every source symbol dropped — recovery purely from repair symbols.
    AllSource,
}

/// One deterministic decode-correctness scenario.
struct Scenario {
    id: &'static str,
    k: usize,
    symbol_size: usize,
    seed: u64,
    sbn: u8,
    loss: LossShape,
    /// Extra repair symbols generated beyond the `L` baseline for decode margin.
    extra_repairs: usize,
}

/// Build deterministic source data: `k` symbols of `symbol_size` bytes each.
fn make_source(k: usize, symbol_size: usize, seed: u64) -> Vec<Vec<u8>> {
    let mut rng = DetRng::new(seed);
    (0..k)
        .map(|_| {
            (0..symbol_size)
                .map(|_| (rng.next_u64() & 0xFF) as u8)
                .collect()
        })
        .collect()
}

/// Resolve a loss shape into the concrete set of dropped source ESIs.
fn dropped_indices(loss: LossShape, k: usize) -> Vec<usize> {
    match loss {
        LossShape::None => Vec::new(),
        LossShape::Scattered(list) => list.iter().copied().filter(|&i| i < k).collect(),
        LossShape::Burst { start, len } => (start..start + len).filter(|&i| i < k).collect(),
        LossShape::Endpoints => {
            if k <= 1 {
                vec![0]
            } else {
                vec![0, k - 1]
            }
        }
        LossShape::AllSource => (0..k).collect(),
    }
}

/// Assemble the received-symbol set surviving a deterministic loss pattern:
/// decoder constraint symbols, the surviving source symbols, and a run of
/// repair symbols generated by the encoder and bound to the decoder's
/// repair equations.
fn build_received(
    encoder: &SystematicEncoder,
    decoder: &InactivationDecoder,
    source: &[Vec<u8>],
    dropped: &[usize],
    extra_repairs: usize,
) -> (Vec<ReceivedSymbol>, usize, usize) {
    let k = source.len();
    let l = decoder.params().l;
    let mut received = decoder.constraint_symbols();

    let mut survived = 0usize;
    for (esi, data) in source.iter().enumerate() {
        if !dropped.contains(&esi) {
            received.push(ReceivedSymbol::source(esi as u32, data.clone()));
            survived += 1;
        }
    }

    let mut repairs = 0usize;
    let repair_upper = (l + extra_repairs) as u32;
    for esi in (k as u32)..repair_upper {
        let (columns, coefficients) = decoder
            .repair_equation(esi)
            .unwrap_or_else(|err| panic!("repair_equation esi={esi} failed: {err:?}"));
        let repair_data = encoder.repair_symbol(esi);
        received.push(ReceivedSymbol::repair(
            esi,
            columns,
            coefficients,
            repair_data,
        ));
        repairs += 1;
    }

    (received, survived, repairs)
}

/// Emit a structured JSON line for one scenario outcome.
fn log_scenario(
    scenario: &Scenario,
    dropped: usize,
    survived: usize,
    repairs: usize,
    outcome: &str,
) {
    println!(
        "{{\"schema\":\"raptorq-decode-matrix-v1\",\"scenario_id\":\"{}\",\"seed\":{},\"k\":{},\"symbol_size\":{},\"sbn\":{},\"loss_pattern\":\"{:?}\",\"dropped\":{dropped},\"survived_source\":{survived},\"repairs\":{repairs},\"outcome\":\"{outcome}\"}}",
        scenario.id, scenario.seed, scenario.k, scenario.symbol_size, scenario.sbn, scenario.loss
    );
}

/// Run one scenario end-to-end and assert exact recovery + proof replay.
fn run_scenario(scenario: &Scenario) {
    let source = make_source(scenario.k, scenario.symbol_size, scenario.seed);
    let encoder = SystematicEncoder::new(&source, scenario.symbol_size, scenario.seed)
        .unwrap_or_else(|| panic!("[{}] encoder construction must succeed", scenario.id));
    let decoder = InactivationDecoder::new(scenario.k, scenario.symbol_size, scenario.seed);

    let dropped = dropped_indices(scenario.loss, scenario.k);
    let (received, survived, repairs) = build_received(
        &encoder,
        &decoder,
        &source,
        &dropped,
        scenario.extra_repairs,
    );
    assert_eq!(
        survived,
        scenario.k - dropped.len(),
        "[{}] surviving source count must match the loss pattern",
        scenario.id
    );

    let object_id = ObjectId::new(OBJECT_ID_HIGH, OBJECT_ID_LOW);
    let result = decoder.decode_with_proof(&received, object_id, scenario.sbn);

    let success = match result {
        Ok(success) => success,
        Err((err, _proof)) => {
            log_scenario(scenario, dropped.len(), survived, repairs, "decode_failure");
            panic!(
                "[{}] decode_with_proof must recover the source: {err:?}",
                scenario.id
            );
        }
    };

    assert_eq!(
        success.result.source, source,
        "[{}] recovered source bytes must equal the original",
        scenario.id
    );

    let proof = success.proof.clone();
    proof
        .replay_and_verify(&received)
        .unwrap_or_else(|err| panic!("[{}] proof replay must verify: {err:?}", scenario.id));

    log_scenario(scenario, dropped.len(), survived, repairs, "ok");
}

const SCENARIOS: &[Scenario] = &[
    Scenario {
        id: "RQ-DEC-NO-LOSS-K16",
        k: 16,
        symbol_size: 24,
        seed: 0x1111_2222_3333_4444,
        sbn: 0,
        loss: LossShape::None,
        extra_repairs: 2,
    },
    Scenario {
        id: "RQ-DEC-SCATTERED-K10",
        k: 10,
        symbol_size: 32,
        seed: 0xAAAA_BBBB_CCCC_DDDD,
        sbn: 7,
        loss: LossShape::Scattered(&[2, 5, 7]),
        extra_repairs: 4,
    },
    Scenario {
        id: "RQ-DEC-BURST-K26",
        k: 26,
        symbol_size: 40,
        seed: 0x0102_0304_0506_0708,
        sbn: 13,
        loss: LossShape::Burst { start: 10, len: 4 },
        extra_repairs: 5,
    },
    Scenario {
        id: "RQ-DEC-ENDPOINTS-K40",
        k: 40,
        symbol_size: 48,
        seed: 0xDEAD_BEEF_CAFE_BABE,
        sbn: 200,
        loss: LossShape::Endpoints,
        extra_repairs: 4,
    },
    Scenario {
        id: "RQ-DEC-ALL-SOURCE-K8",
        k: 8,
        symbol_size: 16,
        seed: 0xFEED_FACE_C0FF_EE00,
        sbn: 42,
        loss: LossShape::AllSource,
        extra_repairs: 6,
    },
];

#[test]
fn raptorq_decode_correctness_matrix_recovers_every_scenario() {
    for scenario in SCENARIOS {
        run_scenario(scenario);
    }
}

#[test]
fn raptorq_decode_is_deterministic_across_runs() {
    // The all-source-erasure case is the most solver-intensive; prove two
    // independent decode runs over identical input recover identical bytes.
    let scenario = &SCENARIOS[4];
    let source = make_source(scenario.k, scenario.symbol_size, scenario.seed);
    let encoder =
        SystematicEncoder::new(&source, scenario.symbol_size, scenario.seed).expect("encoder");
    let dropped = dropped_indices(scenario.loss, scenario.k);

    let decode_once = || {
        let decoder = InactivationDecoder::new(scenario.k, scenario.symbol_size, scenario.seed);
        let (received, _, _) = build_received(
            &encoder,
            &decoder,
            &source,
            &dropped,
            scenario.extra_repairs,
        );
        let object_id = ObjectId::new(OBJECT_ID_HIGH, OBJECT_ID_LOW);
        decoder
            .decode_with_proof(&received, object_id, scenario.sbn)
            .map(|success| success.result.source)
            .expect("decode must succeed")
    };

    assert_eq!(
        decode_once(),
        decode_once(),
        "decode output must be deterministic for a fixed input"
    );
}
