//! ATP replay and trace minimization for deterministic failure reproduction.
//!
//! Extends the existing replay infrastructure in `lab/replay.rs` with ATP-specific
//! trace minimization and failure reproduction capabilities.

use crate::lab::crashpack::AtpCrashpack;
use crate::lab::oracle::{OracleReport, OracleStats};
use crate::trace::{TraceBuffer, TraceEvent};
use serde::{Deserialize, Serialize};
use std::collections::{BTreeSet, HashMap};
use std::path::Path;
use thiserror::Error;

/// ATP replay coordinator for deterministic failure reproduction.
#[derive(Debug)]
pub struct AtpReplayCoordinator {
    /// Original crashpack to replay.
    pub crashpack: AtpCrashpack,
    /// Minimizer configuration.
    pub minimizer_config: TraceMinimizerConfig,
}

impl AtpReplayCoordinator {
    /// Create a new replay coordinator from a crashpack.
    pub fn new(crashpack: AtpCrashpack) -> Self {
        Self {
            crashpack,
            minimizer_config: TraceMinimizerConfig::default(),
        }
    }

    /// Configure the trace minimizer.
    pub fn with_minimizer_config(mut self, config: TraceMinimizerConfig) -> Self {
        self.minimizer_config = config;
        self
    }

    /// Execute ATP replay with the given seeds and oracle configuration.
    pub fn replay(&self) -> Result<AtpReplayResult, ReplayError> {
        // TODO: Integrate with actual lab runtime for deterministic replay
        // This is a placeholder implementation showing the interface

        let mut result = AtpReplayResult {
            original_violations: self.count_original_violations(),
            minimized_trace_length: self.crashpack.trace_events.len(),
            replay_successful: true,
            oracle_results: Vec::new(),
            minimization_stats: MinimizationStats::default(),
        };

        // Apply trace minimization if configured
        if self.minimizer_config.enabled {
            let minimizer = TraceMinimizer::new(self.minimizer_config.clone());
            let minimization_result = minimizer.minimize(&self.crashpack.trace_events)?;

            result.minimized_trace_length = minimization_result.minimized_events.len();
            result.minimization_stats = minimization_result.stats;
        }

        Ok(result)
    }

    /// Generate replay command that can reproduce this failure.
    pub fn generate_replay_command(&self, output_dir: &Path) -> Result<String, ReplayError> {
        let mut cmd = String::from("#!/bin/bash\n");
        cmd.push_str("# ATP Replay Command - Generated by crashpack replay coordinator\n");
        cmd.push_str("# This command reproduces the captured failure deterministically\n\n");

        // Set environment variables for seeds
        for (name, seed) in &self.crashpack.seeds {
            cmd.push_str(&format!("export ATP_SEED_{}={}\n", name.to_uppercase(), seed));
        }

        // Add oracle configuration
        cmd.push_str("\n# Oracle configuration\n");
        for result in &self.crashpack.oracle_results {
            cmd.push_str(&format!("export ATP_ORACLE_{}=enabled\n", result.oracle_name.to_uppercase()));
        }

        // Main replay command
        cmd.push_str("\n# Replay execution\n");
        cmd.push_str(&format!(
            "atp replay {} --trace-file {} --validate-oracles",
            output_dir.join("transfer.atp-trace").display(),
            output_dir.join("manifest").display()
        ));

        // Add minimization if configured
        if self.minimizer_config.enabled {
            cmd.push_str(&format!(" --minimize --reduction-target {}", self.minimizer_config.reduction_target));
        }

        cmd.push_str("\n");
        Ok(cmd)
    }

    fn count_original_violations(&self) -> usize {
        self.crashpack
            .oracle_results
            .iter()
            .map(|r| r.violations.len())
            .sum()
    }
}

/// Configuration for the ATP trace minimizer.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TraceMinimizerConfig {
    /// Enable trace minimization.
    pub enabled: bool,
    /// Target reduction percentage (0.0 - 1.0).
    pub reduction_target: f64,
    /// Maximum number of minimization attempts.
    pub max_attempts: usize,
    /// Preserve oracle-triggering events.
    pub preserve_oracle_events: bool,
    /// Preserve timing-sensitive sequences.
    pub preserve_timing: bool,
}

impl Default for TraceMinimizerConfig {
    fn default() -> Self {
        Self {
            enabled: true,
            reduction_target: 0.3, // Try to reduce by 30%
            max_attempts: 100,
            preserve_oracle_events: true,
            preserve_timing: false,
        }
    }
}

/// ATP trace minimizer for reducing failure traces to essential events.
#[derive(Debug)]
pub struct TraceMinimizer {
    config: TraceMinimizerConfig,
}

impl TraceMinimizer {
    pub fn new(config: TraceMinimizerConfig) -> Self {
        Self { config }
    }

    /// Minimize a trace while preserving failure reproduction.
    pub fn minimize(&self, events: &[TraceEvent]) -> Result<MinimizationResult, ReplayError> {
        if !self.config.enabled || events.is_empty() {
            return Ok(MinimizationResult {
                minimized_events: events.to_vec(),
                stats: MinimizationStats {
                    original_length: events.len(),
                    minimized_length: events.len(),
                    reduction_percentage: 0.0,
                    attempts_made: 0,
                },
            });
        }

        let mut minimized = events.to_vec();
        let mut attempts = 0;
        let original_length = events.len();
        let target_length = (original_length as f64 * (1.0 - self.config.reduction_target)) as usize;

        // Identify essential events that must be preserved
        let essential_indices = self.identify_essential_events(events);

        // Attempt to remove non-essential events
        while minimized.len() > target_length && attempts < self.config.max_attempts {
            let candidates_for_removal = self.find_removal_candidates(&minimized, &essential_indices);

            if candidates_for_removal.is_empty() {
                break; // No more events can be safely removed
            }

            // Try removing a candidate event
            if let Some(candidate_idx) = candidates_for_removal.first() {
                let mut test_trace = minimized.clone();
                test_trace.remove(*candidate_idx);

                // Verify that removing this event doesn't break failure reproduction
                if self.validate_trace_preserves_failure(&test_trace, events) {
                    minimized = test_trace;
                } else {
                    // Mark this event as essential for future iterations
                    // (In a full implementation, we'd track this state)
                }
            }

            attempts += 1;
        }

        let reduction_percentage = (original_length - minimized.len()) as f64 / original_length as f64;

        Ok(MinimizationResult {
            minimized_events: minimized,
            stats: MinimizationStats {
                original_length,
                minimized_length: minimized.len(),
                reduction_percentage,
                attempts_made: attempts,
            },
        })
    }

    fn identify_essential_events(&self, events: &[TraceEvent]) -> BTreeSet<usize> {
        let mut essential = BTreeSet::new();

        for (idx, event) in events.iter().enumerate() {
            // Always preserve certain critical event types
            match event {
                TraceEvent::Spawn { .. } => {
                    if self.config.preserve_oracle_events {
                        essential.insert(idx);
                    }
                }
                TraceEvent::TaskComplete { .. } => {
                    if self.config.preserve_oracle_events {
                        essential.insert(idx);
                    }
                }
                // Add other essential event types as needed
                _ => {}
            }
        }

        // Preserve timing-sensitive sequences if configured
        if self.config.preserve_timing {
            // This would analyze timing-dependent patterns
            // For now, just preserve all events
            for idx in 0..events.len() {
                essential.insert(idx);
            }
        }

        essential
    }

    fn find_removal_candidates(&self, events: &[TraceEvent], essential: &BTreeSet<usize>) -> Vec<usize> {
        let mut candidates = Vec::new();

        for (idx, _event) in events.iter().enumerate() {
            if !essential.contains(&idx) {
                // This event is not marked as essential, so it's a candidate for removal
                candidates.push(idx);
            }
        }

        // Sort by removal priority (remove less important events first)
        // For now, just reverse order (remove later events first)
        candidates.sort_by(|a, b| b.cmp(a));
        candidates
    }

    fn validate_trace_preserves_failure(&self, test_trace: &[TraceEvent], original_trace: &[TraceEvent]) -> bool {
        // This would need to actually run the minimized trace and verify that
        // the same oracle violations are triggered. For now, return a placeholder.

        // Simple heuristic: if we've removed too much, probably not valid
        let reduction = 1.0 - (test_trace.len() as f64 / original_trace.len() as f64);
        reduction < 0.9 // Don't remove more than 90% of events
    }
}

/// Result of ATP replay execution.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AtpReplayResult {
    pub original_violations: usize,
    pub minimized_trace_length: usize,
    pub replay_successful: bool,
    pub oracle_results: Vec<OracleReport>,
    pub minimization_stats: MinimizationStats,
}

/// Result of trace minimization.
#[derive(Debug, Clone)]
pub struct MinimizationResult {
    pub minimized_events: Vec<TraceEvent>,
    pub stats: MinimizationStats,
}

/// Statistics about trace minimization process.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MinimizationStats {
    pub original_length: usize,
    pub minimized_length: usize,
    pub reduction_percentage: f64,
    pub attempts_made: usize,
}

impl Default for MinimizationStats {
    fn default() -> Self {
        Self {
            original_length: 0,
            minimized_length: 0,
            reduction_percentage: 0.0,
            attempts_made: 0,
        }
    }
}

impl MinimizationStats {
    pub fn summary_text(&self) -> String {
        format!(
            "Minimization: {} → {} events ({:.1}% reduction) in {} attempts",
            self.original_length,
            self.minimized_length,
            self.reduction_percentage * 100.0,
            self.attempts_made
        )
    }
}

/// Errors during replay or minimization operations.
#[derive(Debug, Error)]
pub enum ReplayError {
    #[error("Trace minimization failed: {0}")]
    MinimizationFailed(String),
    #[error("Replay validation failed: {0}")]
    ReplayValidationFailed(String),
    #[error("IO error during replay: {0}")]
    Io(#[from] std::io::Error),
    #[error("Oracle validation failed: {0}")]
    OracleValidationFailed(String),
}